### Placement description
version: '3.7'

services:
  nginx-proxy:
    image: 'nginx:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      #      - '81:81'
      - '443:443'
  #    volumes:
  #      - ./data:/data
  #      - ./letsencrypt:/etc/letsencrypt

  postgres_db:
    image: postgres:12
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build: ./backend/
    network_mode: "host"
    environment:
      NODE_ENV: "development"
      DB_CONFIG_HOST: "localhost"
      DB_CONFIG_USERNAME: "postgres"
      DB_CONFIG_PASSWORD: "postgres"
      DB_CONFIG_DATABASE: "postgres"
      DB_CONFIG_PORT: "5433"
    ports:
      - '3004:3004'